### ISSUE TITLE
Unable to compile Zingo-pc

### ISSUE THREAD

**Issue by james-katz** [zingolabs/zingo-pc#112] opened 2023-09-27 12:05 UTC
Tried to compile zingo-pc but it failed.
Using node v16.20.2 and rustc 1.69.0-nightly
Linux Mint 21, kernel 5.15.0-41-generic

full error:
```
Compiling zingolib v0.2.0 (https://github.com/zingolabs/zingolib?branch=dev#7aef7439)
error[E0658]: use of unstable library feature 'is_some_and'
    --> /home/[username]/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/7aef743/zingolib/src/lightclient.rs:1491:14
     |
1491 |             .is_some_and(|trees| {
     |              ^^^^^^^^^^^
     |
     = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
     = help: add `#![feature(is_some_and)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `zingolib` due to previous error
Did not copy "cdylib:zingolib-native"
error Command failed with exit code 101.
```

Steps:
```
git clone https://github.com/zingolabs/zingo-pc.git
cd zingo-pc
nvm use v16.20.2
yarn install
yarn build
```

**Comment by juanky201271** [comment] 2023-09-27 15:19
Thanks @james-katz We are working on a lot of improvements in `zingolib`, and I'm sure I need to adjust a little bit `zingo-pc`. I'm going to do this today, and I let you know... Thanks again.

**Comment by juanky201271** [comment] 2023-09-27 15:25
@james-katz Fixed. Pull all out, and try again, please... and let me know if it is working.

**Comment by james-katz** [comment] 2023-09-27 16:03
@juanky201271 thanks for the quick response. But unfortunately I got the exact same error when trying to compile.
Tried `git pull` ran a cargo clean inside `native`, and then tried to compile, no success.
Tried deleting and cloning the repo again, but got the same error :slightly_frowning_face: 

I'll try to see if it's something I'm doing wrong.

**Comment by james-katz** [comment] 2023-09-27 16:07
@juanky201271 thanks for the quick reply.
unfortunately i got the same error.
tried pulling, tried deleting and cloning again, but got the same error, just the line number is different.

I'll try to see if it is something I'm doing wrong ...

Also, `zingolib` and the cli compiles ok, I'm getting this error only when trying to compile zingo-pc

**Comment by juanky201271** [comment] 2023-09-27 16:11
can you paste the new error even if seems the same... please...

**Comment by james-katz** [comment] 2023-09-27 16:13
```
   Compiling zingolib v0.2.0 (https://github.com/zingolabs/zingolib?branch=dev#6e0db927)
error[E0658]: use of unstable library feature 'is_some_and'
    --> /home/thiago/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/6e0db92/zingolib/src/lightclient.rs:1523:14
     |
1523 |             .is_some_and(|trees| {
     |              ^^^^^^^^^^^
     |
     = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
     = help: add `#![feature(is_some_and)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `zingolib` due to previous error
Did not copy "cdylib:zingolib-native"
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by james-katz** [comment] 2023-09-27 16:14
```
Compiling zingolib v0.2.0 (https://github.com/zingolabs/zingolib?branch=dev#6e0db927)
error[E0658]: use of unstable library feature 'is_some_and'
    --> /home/user/.cargo/git/checkouts/zingolib-2003bc87acd6fa69/6e0db92/zingolib/src/lightclient.rs:1523:14
     |
1523 |             .is_some_and(|trees| {
     |              ^^^^^^^^^^^
     |
     = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
     = help: add `#![feature(is_some_and)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `zingolib` due to previous error
Did not copy "cdylib:zingolib-native"
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by juanky201271** [comment] 2023-09-27 16:22
I would say, maybe I'm wrong... that the problem is the rust version, I think you need to upgrade it with `rustup update`...

I have this: `rustc 1.74.0-nightly (5ae769f06 2023-09-26)`

honestly I'm not sure, but this update I think is harmless for you.

**Comment by james-katz** [comment] 2023-09-27 16:54
"The simplest solution is often the best one."
Yes, upgrading my rust version fixes my problem. Thanks.

**Comment by juanky201271** [comment] 2023-09-27 16:55
closing then....

**Closed as completed by juanky201271** 2023-09-27 16:55 UTC
